name: Deploy to Minikube

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')  # Genera un tag único con la fecha y hora
          docker build -t agustinribotta/springboot-app:$VERSION .
          docker push agustinribotta/springboot-app:$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Guarda la versión para los siguientes pasos

      - name: Update Kubernetes Deployment File
        run: |
          sed -i "s|image: agustinribotta/springboot-app:.*|image: agustinribotta/springboot-app:${{ env.VERSION }}|g" kubernetes/deployment.yaml

      - name: Configure SSH for GitHub
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$ACTIONS_DEPLOY_KEY" > ~/.ssh/githubActions
          chmod 600 ~/.ssh/githubActions
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add kubernetes/deployment.yaml
          git commit -m "Update image to version ${{ env.VERSION }}"
          git push origin main
