name: Deploy to Minikube

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t agustinribotta/springboot-app:latest .
          docker push agustinribotta/springboot-app:latest

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          minikube start --driver=docker
          minikube addons enable ingress

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0

      - name: Configure kubectl context
        run: |
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy.yaml
          kubectl apply -f service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services
