name: Update Image Version

on:
  push:
    branches:
      - main

jobs:
  update-image-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to work with the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH key for Git authentication
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Step 3: Generate a unique version using the current timestamp
      - name: Generate version using timestamp
        id: generate_version
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S') 
          echo "Generated version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save version to the environment variable

      # Step 4: Verify if the VERSION variable is correctly passed
      - name: Verify VERSION variable
        run: echo "The generated version is:$VERSION"
        
      - name: Update Docker Image Version in Deployment YAML
        run: |
          VERSION=${{ env.VERSION }}
          sed -i "s|agustinribotta/springboot-app:.*|agustinribotta/springboot-app:$VERSION|" kubernetes/deployment.yaml
          echo "" >> kubernetes/deployment.yaml  # Add a forced change (e.g., new line)
        

      # Step 6: Check if there are changes
      - name: Check if there are changes
        run: git status

      # Step 7: Commit the changes and push to the repository
      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin git@github.com:AgustinRibotta/demo.git

          # Check if there are changes to commit
          if git diff --quiet kubernetes/deployment.yaml; then
            echo "No changes to commit"
          else
            git add kubernetes/deployment.yaml
            git commit -m "Update image to version $VERSION"
            git push origin main  # Solo push si hay cambios
          fi
